# -*- coding: utf-8 -*-
"""Lista 2 - Pré Processamento(1).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Us2SFBqa7KbO1uO6GWbDneaHg0ND2m8E

1) Leia o Arquivo Iris.csv (https://www.kaggle.com/uciml/iris/download) em um Data Frame.
"""

import pandas as pd
import numpy as np
#https://www.kaggle.com/uciml/iris/download
df = pd.read_csv('/Iris.csv')
df

"""2) Print os primeiros 5 registros do DataFrame"""

df.head()

"""3) Print os ultimos 5 registros do DataFrame."""

df.tail()

"""4) Mostre apenas as duas primeiras colunas do DataFrame"""

df.iloc[:, 0:2]

"""5) Mostre apenas a última coluna do DataFrame"""

df.iloc[:, -1]

"""6) Mostre apenas os registros da 'Iris-virginica' do DataFrame"""

df.query('Species == "Iris-virginica"')

"""7) Mostre todos os registros com excessão da 'Iris-virginica' do DataFrame"""

df.query('Species != "Iris-virginica"')

"""8) Mostre os tipos de dados do DataFrame"""

df.dtypes

"""9) Calcule a Media das colunas numericas do DataFrame"""

df[['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']].mean()

"""10) Calcule a Median da coluna 'SepalLengthCm' do DataFrame"""

df['SepalLengthCm'].median()

"""11) Mostre o maior valor da coluna 'PetalWidthCm'"""

df['PetalWidthCm'].max()

"""12) Mostre o menor valor da coluna 'PetalLengthCm'"""

df['PetalLengthCm'].min()

"""13) Mostre apenas os registros do DataFrame cujo o valor da coluna 'PetalLengthCm' são maior que 5.10"""

df.query('PetalLengthCm >= 5.10')

"""14) Mostre o DataFrame apenas do indice 7 ao 15 (inclusive)"""

df.iloc[7:16]

"""15) Mostre a quantidade de registros de cada especie"""

df['Species'].value_counts()

"""16) Mostre porcentagem de registros de cada especie"""

df['Species'].value_counts(normalize=True)

"""17) Crie outro DataFrame apenas com as colunas 'PetalWidthCm' e 'Species'"""

df_2 = df.loc[:, ["PetalWidthCm", "Species"]]
df_2

"""18) Crie um boxplot da coluna SepalLengthCm, não esqueça de colocar o nome dos eixos"""

import matplotlib.pyplot as plt

plt.boxplot(df['SepalLengthCm'])
plt.xlabel('Sepal Length (Cm)')
plt.ylabel('Valores')
plt.show()

"""19) Crie um boxplot da coluna SepalWidthCm, não esqueça de colocar o nome dos eixos"""

plt.boxplot(df['SepalWidthCm'])
plt.xlabel('Sepal Width (Cm)')
plt.ylabel('Valores')
plt.show()

"""20) Crie um boxplot da coluna PetalLengthCm, não esqueça de colocar o nome dos eixos"""

plt.boxplot(df['PetalLengthCm'])
plt.xlabel('Petal Length (Cm)')
plt.ylabel('Valores')
plt.show()

"""21) Crie um boxplot da coluna PetalWidthCm, não esqueça de colocar o nome dos eixos"""

plt.boxplot(df['PetalWidthCm'])
plt.xlabel('Petal Width (Cm)')
plt.ylabel('Valores')
plt.show()

"""22) Qual(is) coluna(s) possue(m) outliers?

De acordo com os 'boxplots' acima, apenas na coluna 'SepalWidthCm' é possível identificar outliers (4).

23) Faça um Scatter plot entre SepalLengthCm e PetalLengthCm
"""

import matplotlib.pyplot as plt

plt.scatter(df['SepalLengthCm'], df['PetalLengthCm'])
plt.xlabel('Sepal Length (Cm)')
plt.ylabel('Petal Length (Cm)')
plt.title('Scatter Plot entre as colunas Sepal Length (Cm) e Petal Length (Cm)')
plt.show()

"""24) Faça um Scatter plot entre SepalWidthCm e PetalWidthCm"""

plt.scatter(df['SepalWidthCm'], df['PetalWidthCm'])
plt.xlabel('Sepal Width (Cm)')
plt.ylabel('Petal Width (Cm)')
plt.title('Scatter Plot entre as colunas Sepal Width (Cm) e Petal Width (Cm)')
plt.show()

"""25) Faça a tabela de Correlação entre as colunas"""

import seaborn as sns

correlacao = df.corr()
sns.heatmap(correlacao, annot=True, cmap='coolwarm')
plt.title('Tabela de Correlação')
plt.show()

"""26) Faça um Describe do DataFrame"""

df.describe()